### ISSUE TITLE
[lecture_comparison] Many code cells are not compiled or are looking strange

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#23]
Hi @mmcky , I noticed an important issue in ``MYST`` that
- many code cells are not compiled or just look very strange there

For example, in lecture [cake_eating_numerical](https://quantecon.github.io/lecture-python.myst/cake_eating_numerical.html), almost all code cells have this issue and I label them with red lines.

Please see not compiled code cells:
![Screen Shot 2021-01-03 at 9 40 35 am](https://user-images.githubusercontent.com/53931041/103467896-c8487100-4da7-11eb-9e13-fcfa0b767414.png)

Please see strange code cells:
![Screen Shot 2021-01-03 at 9 41 44 am](https://user-images.githubusercontent.com/53931041/103467915-f1690180-4da7-11eb-9b25-d2ee15b3faab.png)

**These issues are widely existing in the following lectures (updated)**:
- [29_cake_eating_numerical](https://quantecon.github.io/lecture-python.myst/cake_eating_numerical.html)
- [30_optgrowth](https://quantecon.github.io/lecture-python.myst/optgrowth.html)
- [31_optgrowth_fast](https://quantecon.github.io/lecture-python.myst/optgrowth_fast.html)
- [32_coleman_policy_iter](https://quantecon.github.io/lecture-python.myst/coleman_policy_iter.html)
- [33_egm_policy_iter](https://quantecon.github.io/lecture-python.myst/egm_policy_iter.html)
- [34_ifp](https://quantecon.github.io/lecture-python.myst/ifp.html)
- [36_odu](https://quantecon.github.io/lecture-python.myst/odu.html)
- [50_markov_perf](https://quantecon.github.io/lecture-python.myst/markov_perf.html)

**Comment by mmcky** [comment]
Thanks @shlff this should now be fixed by #16

**Comment by shlff** [comment]
Thanks @mmcky . This issue has been solved for almost all lectures I mentioned above, except for lecture ``36_odu``. Please see the most-recent preview for 36_odu from #16, [here](https://5ff580ff1bec79c49f4be5b2--nostalgic-wright-5fa355.netlify.app/odu.html).

**Comment by mmcky** [comment]
thanks @shlff `odu` wasn't changed in #16 so it must be due to a different issue. Would you have time to review and see why that lecture may not be executing?

**Comment by mmcky** [comment]
@shlff is this still an issue?

**Comment by shlff** [comment]
Thanks @mmcky . I checked all affected lectures in the most-recent preview from #16 , but this issue still exists in lecture ``36_odu``, please see the most-recent preview from #16 for this lecture: https://5ffe520ba040b2461b6bc742--nostalgic-wright-5fa355.netlify.app/odu.html.

**Comment by mmcky** [comment]
`odu` execution was timing out. This should now be fixed by 9a791ca
